---
- name: Ensure package list is provided
  fail:
    msg: "You must provide a list of packages"
  when: package_list | length == 0

- name: Install packages on Debian-based systems
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  when: ansible_os_family == "Debian"
  tags: debian

- name: Install packages on RedHat-based systems
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  when: ansible_os_family == "RedHat"
  tags: redhat

- name: Install packages on SUSE-based systems
  zypper:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  when: ansible_os_family == "Suse"
  tags: suse

- name: Install packages on Arch-based systems
  pacman:
    name: "{{ item }}"
    state: present
  loop: "{{ package_list }}"
  when: ansible_os_family == "Archlinux"
  tags: archlinux
