---
- name: Ensure service name is provided
  fail:
    msg: "You must provide a service name"
  when: service_name is undefined

- name: Ensure service state is provided
  fail:
    msg: "You must provide a service state (started/stopped/restarted)"
  when: service_state is undefined

- name: Manage service on Debian-based systems
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  when: ansible_os_family == "Debian"
  tags: debian

- name: Manage service on RedHat-based systems
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  when: ansible_os_family == "RedHat"
  tags: redhat

- name: Manage service on SUSE-based systems
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  when: ansible_os_family == "Suse"
  tags: suse

- name: Manage service on Arch-based systems
  service:
    name: "{{ service_name }}"
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
  when: ansible_os_family == "Archlinux"
  tags: archlinux
