---
- name: Configure Firewall
  hosts: all
  become: yes
  vars:
    allowed_ports:
      - 22
      - 80
      - 443
  tasks:
    - name: Install firewalld
      ansible.builtin.package:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable firewalld
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Allow ports through firewall
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      loop: "{{ allowed_ports }}"
      when: ansible_os_family == "RedHat"
