---
- name: Deploy Apache Web Server
  hosts: all
  become: yes
  vars:
    apache_package_name:
      Debian: apache2
      RedHat: httpd
      Suse: apache2
      Archlinux: apache
    apache_service_name:
      Debian: apache2
      RedHat: httpd
      Suse: apache2
      Archlinux: httpd
    service_state: "started"  # Could be "started", "stopped", or "restarted"
    service_enabled: True
    service_name: "{{ apache_service_name[ansible_os_family] | default('apache2') }}"
    package_name: "{{ apache_package_name[ansible_os_family] | default('apache2') }}"
  tasks:
    - name: Install Apache package
      include_role:
        name: install_packages
      vars:
        package_list: ["{{ package_name }}"]

    - name: Manage Apache service
      include_role:
        name: manage_service
      vars:
        service_name: "{{ service_name }}"
        service_state: "{{ service_state }}"
        service_enabled: "{{ service_enabled }}"

    - name: Create a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <body>
              <h1>Welcome to Apache on {{ ansible_os_family }}</h1>
            </body>
          </html>
