---
- name: Install a package on multiple Linux systems
  hosts: all
  become: yes
  vars:
    package_name: ""
  tasks:
    - name: Ensure package name is provided
      fail:
        msg: "You must provide a package name"
      when: package_name == ""

    - name: Install package on Debian-based systems
      apt:
        name: "{{ package_name }}"
        state: present
      when: ansible_os_family == "Debian"
      tags: debian

    - name: Install package on RedHat-based systems
      yum:
        name: "{{ package_name }}"
        state: present
      when: ansible_os_family == "RedHat"
      tags: redhat

    - name: Install package on SUSE-based systems
      zypper:
        name: "{{ package_name }}"
        state: present
      when: ansible_os_family == "Suse"
      tags: suse

    - name: Install package on Arch-based systems
      pacman:
        name: "{{ package_name }}"
        state: present
      when: ansible_os_family == "Archlinux"
      tags: archlinux
