---
- name: Install packages on multiple Linux systems
  hosts: all
  become: yes
  vars:
    package_list: []
  tasks:
    - name: Install provided packages
      include_role:
        name: install_packages
