---
- name: Manage service from variables
  hosts: all
  become: yes
  vars:
    service_name: ""  # Default service name
  tasks:
    - name: Ensure service_name is provided
      fail:
        msg: "You must provide a service name"
      when: service_name == ""

    - name: manage service
      service:
        name: "{{ service_name }}"
        state: "{{ service_state }}"
