---
- name: Manage service from variables
  hosts: all
  become: yes
  vars:
    service_name: ""  # Default service name
    service_state: ""
    service_enabled: ""
  tasks:
    - name: Manage {{ service_name }} service
      include_role:
        name: manage_service
